### ISSUE TITLE
The extension has stopped working

### ISSUE THREAD

**Issue by dinuionut** [greatghoul/hubstaff-panel#1]
Seems to be related to the fact that the hubstaff reports page requires JavaScript now in order to display the data.

**Comment by greatghoul** [comment]
Thank you for your feedback.

My customer do not use hubstaff recently, so I have no data available in new weeks, but I think I can fix this using former data.

I will try to fix this in 1 or 2 days.

**Comment by greatghoul** [comment]
it's fixed in the new release, if it works for you, please let me know.

**Comment by dinuionut** [comment]
Yes, it does. Thanks a lot!

**Comment by dinuionut** [comment]
I think that you can use https://app.hubstaff.com/dashboard/me for the dashboard link, otherwise it loads the "team" dashboard (if you have a team too).

**Comment by greatghoul** [comment]
I changed the url to dashboard/me in v1.0.2

https://github.com/greatghoul/hubstaff-panel/releases/tag/v1.0.2

**Comment by dinuionut** [comment]
Tested, working fine!
